#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NYASApp.Resource", IsApplication=true)]

namespace NYASApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070002
			public const int CarerInfoStrings = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int DefaultHomeScreenStrings = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int KidsZoneScreenStrings = 2131165185;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040003
			public const int backgroundPeach = 2130968579;
			
			// aapt resource value: 0x7f04000a
			public const int blueGradientEnd = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int blueGradientStart = 2130968585;
			
			// aapt resource value: 0x7f04000e
			public const int greenGradientEnd = 2130968590;
			
			// aapt resource value: 0x7f04000d
			public const int greenGradientStart = 2130968589;
			
			// aapt resource value: 0x7f040002
			public const int infoTextRed = 2130968578;
			
			// aapt resource value: 0x7f04000c
			public const int orangeGradientEnd = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int orangeGradientStart = 2130968587;
			
			// aapt resource value: 0x7f040005
			public const int peachGradientEnd = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int peachGradientStart = 2130968580;
			
			// aapt resource value: 0x7f040010
			public const int purpleGradientEnd = 2130968592;
			
			// aapt resource value: 0x7f04000f
			public const int purpleGradientStart = 2130968591;
			
			// aapt resource value: 0x7f040007
			public const int redGradientEnd = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int redGradientStart = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int redGradientStroke = 2130968584;
			
			// aapt resource value: 0x7f040000
			public const int transparent = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int white = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int buttonCornerRadius = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int buttonPadding = 2131034113;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon_Example = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int NYAS_App_Logo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int NYAS_Logo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Rectangle = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int rectangle_blue_gradient = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int rectangle_green_gradient = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int rectangle_orange_gradient = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int rectangle_peach_gradient = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int rectangle_purple_gradient = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int rectangle_red_gradient = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Speech_Bubble_Empty = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Splash_Screen_One = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Splash_Screen_Two = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080009
			public const int BottomInfoText = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int SplashImage = 2131230730;
			
			// aapt resource value: 0x7f080005
			public const int buttonBottomLeft = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int buttonBottomRight = 2131230724;
			
			// aapt resource value: 0x7f080001
			public const int buttonTopLeft = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int buttonTopRight = 2131230723;
			
			// aapt resource value: 0x7f080006
			public const int nyasLogo = 2131230726;
			
			// aapt resource value: 0x7f080000
			public const int relativeLayout1 = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int relativelayoutSpeechBubble = 2131230722;
			
			// aapt resource value: 0x7f080007
			public const int speechBubble = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int speechBubbleText = 2131230728;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int HomepageLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Splash_Screen_Layout = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f06000c
			public const int AboutUs = 2131099660;
			
			// aapt resource value: 0x7f06000e
			public const int AboutUsDetailed = 2131099662;
			
			// aapt resource value: 0x7f060009
			public const int Advice = 2131099657;
			
			// aapt resource value: 0x7f06000d
			public const int BecomeACarer = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int BubbleMsg1 = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int BubbleMsg2 = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int BubbleMsg3 = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int BubbleMsg4 = 2131099666;
			
			// aapt resource value: 0x7f060005
			public const int CarerInfo = 2131099653;
			
			// aapt resource value: 0x7f06000a
			public const int ContactNYAS = 2131099658;
			
			// aapt resource value: 0x7f060003
			public const int GetInTouch = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int KidsZone = 2131099650;
			
			// aapt resource value: 0x7f06000b
			public const int MoreCarerInfo = 2131099659;
			
			// aapt resource value: 0x7f060004
			public const int MoreInfo = 2131099652;
			
			// aapt resource value: 0x7f060008
			public const int NotFair = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int SchoolProblems = 2131099655;
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int feelingBlue = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
