#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NYASApp.Resource", IsApplication=true)]

namespace NYASApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f080002
			public const int CarerInfoStrings = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int DefaultHomeScreenStrings = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int KidsZoneScreenStrings = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int LoginStrings = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int MoreInfoStrings = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int MyNYASStrings = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int OptionStrings = 2131230726;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040004
			public const int backgroundOrange = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int backgroundPeach = 2130968579;
			
			// aapt resource value: 0x7f04000b
			public const int blueGradientEnd = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int blueGradientStart = 2130968586;
			
			// aapt resource value: 0x7f040012
			public const int calendarBackground = 2130968594;
			
			// aapt resource value: 0x7f04000f
			public const int greenGradientEnd = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public const int greenGradientStart = 2130968590;
			
			// aapt resource value: 0x7f040002
			public const int infoTextRed = 2130968578;
			
			// aapt resource value: 0x7f04000d
			public const int orangeGradientEnd = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int orangeGradientStart = 2130968588;
			
			// aapt resource value: 0x7f040006
			public const int peachGradientEnd = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int peachGradientStart = 2130968581;
			
			// aapt resource value: 0x7f040011
			public const int purpleGradientEnd = 2130968593;
			
			// aapt resource value: 0x7f040010
			public const int purpleGradientStart = 2130968592;
			
			// aapt resource value: 0x7f040008
			public const int redGradientEnd = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int redGradientStart = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int redGradientStroke = 2130968585;
			
			// aapt resource value: 0x7f040000
			public const int transparent = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int white = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060002
			public const int ButtonTextSize = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int SpecialButtonSize = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int buttonCornerRadius = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int buttonPadding = 2131099649;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int alternative_orange_gradient = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon_Example = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int NYAS_App_Logo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int NYAS_Logo = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int People_Example = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Rectangle = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int rectangle_blue_gradient = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int rectangle_green_gradient = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int rectangle_orange_gradient = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int rectangle_peach_gradient = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int rectangle_purple_gradient = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int rectangle_red_gradient = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Speech_Bubble_Empty = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Splash_Screen_One = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Splash_Screen_Two = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0016
			public const int BottomInfoText = 2131361814;
			
			// aapt resource value: 0x7f0a000a
			public const int CallFreePhone = 2131361802;
			
			// aapt resource value: 0x7f0a0007
			public const int ConactRelativeLayout = 2131361799;
			
			// aapt resource value: 0x7f0a000c
			public const int ContactArtImage = 2131361804;
			
			// aapt resource value: 0x7f0a0009
			public const int ContactContent = 2131361801;
			
			// aapt resource value: 0x7f0a0008
			public const int ContactTitle = 2131361800;
			
			// aapt resource value: 0x7f0a001e
			public const int EnterAgeField = 2131361822;
			
			// aapt resource value: 0x7f0a001f
			public const int EnterEmailField = 2131361823;
			
			// aapt resource value: 0x7f0a001d
			public const int EnterNameField = 2131361821;
			
			// aapt resource value: 0x7f0a0020
			public const int EnterPhoneField = 2131361824;
			
			// aapt resource value: 0x7f0a0018
			public const int InformationArtImage = 2131361816;
			
			// aapt resource value: 0x7f0a001a
			public const int InformationContent = 2131361818;
			
			// aapt resource value: 0x7f0a0017
			public const int InformationRelativeLayout = 2131361815;
			
			// aapt resource value: 0x7f0a0019
			public const int InformationTitle = 2131361817;
			
			// aapt resource value: 0x7f0a001b
			public const int ProfileRelativeLayout = 2131361819;
			
			// aapt resource value: 0x7f0a001c
			public const int ProfileTitle = 2131361820;
			
			// aapt resource value: 0x7f0a0021
			public const int SaveChanges = 2131361825;
			
			// aapt resource value: 0x7f0a000b
			public const int SendEmail = 2131361803;
			
			// aapt resource value: 0x7f0a0022
			public const int SplashImage = 2131361826;
			
			// aapt resource value: 0x7f0a0006
			public const int ViewAppointments = 2131361798;
			
			// aapt resource value: 0x7f0a0002
			public const int appointmentListView = 2131361794;
			
			// aapt resource value: 0x7f0a0000
			public const int appointmentsRelativeLayout1 = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int appointmentsTitle = 2131361793;
			
			// aapt resource value: 0x7f0a0012
			public const int buttonBottomLeft = 2131361810;
			
			// aapt resource value: 0x7f0a0011
			public const int buttonBottomRight = 2131361809;
			
			// aapt resource value: 0x7f0a000e
			public const int buttonTopLeft = 2131361806;
			
			// aapt resource value: 0x7f0a0010
			public const int buttonTopRight = 2131361808;
			
			// aapt resource value: 0x7f0a0003
			public const int calendarRelativeLayout1 = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int calendarView1 = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int makeAppointmentButton = 2131361797;
			
			// aapt resource value: 0x7f0a0013
			public const int nyasLogo = 2131361811;
			
			// aapt resource value: 0x7f0a000d
			public const int relativeLayout1 = 2131361805;
			
			// aapt resource value: 0x7f0a000f
			public const int relativelayoutSpeechBubble = 2131361807;
			
			// aapt resource value: 0x7f0a0014
			public const int speechBubble = 2131361812;
			
			// aapt resource value: 0x7f0a0015
			public const int speechBubbleText = 2131361813;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050001
			public const int CarerInfoContext = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int IAWhatsNYASDoContext = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int testInt = 2131034114;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Appointments_Activity_Layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Calendar_Activity_Layout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Contact_Activity_Layout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int HomepageLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Information_Activity_Layout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Profile_Activity_Layout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Splash_Screen_Layout = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f07001c
			public const int AboutUs = 2131165212;
			
			// aapt resource value: 0x7f070030
			public const int AboutUsDetailed = 2131165232;
			
			// aapt resource value: 0x7f070019
			public const int Advice = 2131165209;
			
			// aapt resource value: 0x7f07001d
			public const int BecomeACarer = 2131165213;
			
			// aapt resource value: 0x7f070034
			public const int BubbleMsg1 = 2131165236;
			
			// aapt resource value: 0x7f070035
			public const int BubbleMsg2 = 2131165237;
			
			// aapt resource value: 0x7f070036
			public const int BubbleMsg3 = 2131165238;
			
			// aapt resource value: 0x7f070037
			public const int BubbleMsg4 = 2131165239;
			
			// aapt resource value: 0x7f070038
			public const int BubbleMsg5 = 2131165240;
			
			// aapt resource value: 0x7f070032
			public const int CarefulOptions = 2131165234;
			
			// aapt resource value: 0x7f070015
			public const int CarerInfo = 2131165205;
			
			// aapt resource value: 0x7f070006
			public const int CarerInfoContent = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int CarerInfoTitle = 2131165189;
			
			// aapt resource value: 0x7f07002e
			public const int ChangeToWidgits = 2131165230;
			
			// aapt resource value: 0x7f07002f
			public const int ComingSoon = 2131165231;
			
			// aapt resource value: 0x7f07003f
			public const int Confirm = 2131165247;
			
			// aapt resource value: 0x7f070007
			public const int ContactInstructions = 2131165191;
			
			// aapt resource value: 0x7f07001a
			public const int ContactNYAS = 2131165210;
			
			// aapt resource value: 0x7f070029
			public const int ContactUs = 2131165225;
			
			// aapt resource value: 0x7f070041
			public const int CorrectPin = 2131165249;
			
			// aapt resource value: 0x7f070039
			public const int CustomBubbleMsg1 = 2131165241;
			
			// aapt resource value: 0x7f07003a
			public const int CustomBubbleMsg2Part1Of2 = 2131165242;
			
			// aapt resource value: 0x7f07003b
			public const int CustomBubbleMsg2Part2Of2 = 2131165243;
			
			// aapt resource value: 0x7f07003c
			public const int CustomBubbleMsg3Part1Of2 = 2131165244;
			
			// aapt resource value: 0x7f07003d
			public const int CustomBubbleMsg3Part2Of2 = 2131165245;
			
			// aapt resource value: 0x7f07002c
			public const int DeleteProfile = 2131165228;
			
			// aapt resource value: 0x7f07002d
			public const int DelteAppointments = 2131165229;
			
			// aapt resource value: 0x7f070025
			public const int Donate = 2131165221;
			
			// aapt resource value: 0x7f070009
			public const int EnterYourAge = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int EnterYourEmail = 2131165194;
			
			// aapt resource value: 0x7f070008
			public const int EnterYourName = 2131165192;
			
			// aapt resource value: 0x7f07000b
			public const int EnterYourPhoneNumber = 2131165195;
			
			// aapt resource value: 0x7f07000e
			public const int Freephone = 2131165198;
			
			// aapt resource value: 0x7f070013
			public const int GetInTouch = 2131165203;
			
			// aapt resource value: 0x7f07000d
			public const int HowToConactNYAS = 2131165197;
			
			// aapt resource value: 0x7f070023
			public const int HowToGetHelp = 2131165219;
			
			// aapt resource value: 0x7f070004
			public const int IAWhatsNYASDoContent = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int IAWhatsNYASDoTitle = 2131165187;
			
			// aapt resource value: 0x7f070012
			public const int KidsZone = 2131165202;
			
			// aapt resource value: 0x7f070010
			public const int MakeAppointment = 2131165200;
			
			// aapt resource value: 0x7f07001b
			public const int MoreCarerInfo = 2131165211;
			
			// aapt resource value: 0x7f070014
			public const int MoreInfo = 2131165204;
			
			// aapt resource value: 0x7f070028
			public const int MyAppointments = 2131165224;
			
			// aapt resource value: 0x7f070026
			public const int MyNYAS = 2131165222;
			
			// aapt resource value: 0x7f070027
			public const int MyProfile = 2131165223;
			
			// aapt resource value: 0x7f070018
			public const int NotFair = 2131165208;
			
			// aapt resource value: 0x7f07002a
			public const int Options = 2131165226;
			
			// aapt resource value: 0x7f070033
			public const int PersonalSpace = 2131165235;
			
			// aapt resource value: 0x7f07003e
			public const int Pin = 2131165246;
			
			// aapt resource value: 0x7f070042
			public const int PinConfirmed = 2131165250;
			
			// aapt resource value: 0x7f070031
			public const int PinInstructions = 2131165233;
			
			// aapt resource value: 0x7f070024
			public const int RateOurService = 2131165220;
			
			// aapt resource value: 0x7f07002b
			public const int ResetPin = 2131165227;
			
			// aapt resource value: 0x7f07000c
			public const int SaveChanges = 2131165196;
			
			// aapt resource value: 0x7f070017
			public const int SchoolProblems = 2131165207;
			
			// aapt resource value: 0x7f07000f
			public const int SendEmail = 2131165199;
			
			// aapt resource value: 0x7f070002
			public const int Slogan = 2131165186;
			
			// aapt resource value: 0x7f07001e
			public const int SpecialCharacter1 = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int SpecialCharacter2 = 2131165215;
			
			// aapt resource value: 0x7f070020
			public const int SpecialCharacter3 = 2131165216;
			
			// aapt resource value: 0x7f070021
			public const int SpecialCharacter4 = 2131165217;
			
			// aapt resource value: 0x7f070011
			public const int ViewAppointments = 2131165201;
			
			// aapt resource value: 0x7f070022
			public const int WhatsNYAS = 2131165218;
			
			// aapt resource value: 0x7f070040
			public const int WrongPin = 2131165248;
			
			// aapt resource value: 0x7f070001
			public const int app_name = 2131165185;
			
			// aapt resource value: 0x7f070016
			public const int feelingBlue = 2131165206;
			
			// aapt resource value: 0x7f070000
			public const int hello = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int calendarTextStyle = 2131296256;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
