#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NYASApp.Resource", IsApplication=true)]

namespace NYASApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070002
			public const int CarerInfoStrings = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int DefaultHomeScreenStrings = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int KidsZoneScreenStrings = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int LoginStrings = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int MoreInfoStrings = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int MyNYASStrings = 2131165189;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040004
			public const int backgroundOrange = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int backgroundPeach = 2130968579;
			
			// aapt resource value: 0x7f04000b
			public const int blueGradientEnd = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int blueGradientStart = 2130968586;
			
			// aapt resource value: 0x7f040012
			public const int calendarBackground = 2130968594;
			
			// aapt resource value: 0x7f04000f
			public const int greenGradientEnd = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public const int greenGradientStart = 2130968590;
			
			// aapt resource value: 0x7f040002
			public const int infoTextRed = 2130968578;
			
			// aapt resource value: 0x7f04000d
			public const int orangeGradientEnd = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int orangeGradientStart = 2130968588;
			
			// aapt resource value: 0x7f040006
			public const int peachGradientEnd = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int peachGradientStart = 2130968581;
			
			// aapt resource value: 0x7f040011
			public const int purpleGradientEnd = 2130968593;
			
			// aapt resource value: 0x7f040010
			public const int purpleGradientStart = 2130968592;
			
			// aapt resource value: 0x7f040008
			public const int redGradientEnd = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int redGradientStart = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int redGradientStroke = 2130968585;
			
			// aapt resource value: 0x7f040000
			public const int transparent = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int white = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050002
			public const int ButtonTextSize = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int SpecialButtonSize = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int buttonCornerRadius = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int buttonPadding = 2131034113;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int alternative_orange_gradient = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon_Example = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int NYAS_App_Logo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int NYAS_Logo = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Rectangle = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int rectangle_blue_gradient = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int rectangle_green_gradient = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int rectangle_orange_gradient = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int rectangle_peach_gradient = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int rectangle_purple_gradient = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int rectangle_red_gradient = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Speech_Bubble_Empty = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Splash_Screen_One = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Splash_Screen_Two = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09000f
			public const int BottomInfoText = 2131296271;
			
			// aapt resource value: 0x7f090010
			public const int SplashImage = 2131296272;
			
			// aapt resource value: 0x7f090005
			public const int ViewAppointments = 2131296261;
			
			// aapt resource value: 0x7f090001
			public const int appointmentListView = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int appointmentsRelativeLayout1 = 2131296256;
			
			// aapt resource value: 0x7f09000b
			public const int buttonBottomLeft = 2131296267;
			
			// aapt resource value: 0x7f09000a
			public const int buttonBottomRight = 2131296266;
			
			// aapt resource value: 0x7f090007
			public const int buttonTopLeft = 2131296263;
			
			// aapt resource value: 0x7f090009
			public const int buttonTopRight = 2131296265;
			
			// aapt resource value: 0x7f090002
			public const int calendarRelativeLayout1 = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int calendarView1 = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int makeAppointmentButton = 2131296260;
			
			// aapt resource value: 0x7f09000c
			public const int nyasLogo = 2131296268;
			
			// aapt resource value: 0x7f090006
			public const int relativeLayout1 = 2131296262;
			
			// aapt resource value: 0x7f090008
			public const int relativelayoutSpeechBubble = 2131296264;
			
			// aapt resource value: 0x7f09000d
			public const int speechBubble = 2131296269;
			
			// aapt resource value: 0x7f09000e
			public const int speechBubbleText = 2131296270;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Appointments_Activity_Layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Calendar_Activity_Layout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int HomepageLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Splash_Screen_Layout = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f06000e
			public const int AboutUs = 2131099662;
			
			// aapt resource value: 0x7f06001c
			public const int AboutUsDetailed = 2131099676;
			
			// aapt resource value: 0x7f06000b
			public const int Advice = 2131099659;
			
			// aapt resource value: 0x7f06000f
			public const int BecomeACarer = 2131099663;
			
			// aapt resource value: 0x7f06001e
			public const int BubbleMsg1 = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int BubbleMsg2 = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int BubbleMsg3 = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int BubbleMsg4 = 2131099681;
			
			// aapt resource value: 0x7f060007
			public const int CarerInfo = 2131099655;
			
			// aapt resource value: 0x7f060023
			public const int Confirm = 2131099683;
			
			// aapt resource value: 0x7f06000c
			public const int ContactNYAS = 2131099660;
			
			// aapt resource value: 0x7f06001a
			public const int ContactUs = 2131099674;
			
			// aapt resource value: 0x7f060025
			public const int CorrectPin = 2131099685;
			
			// aapt resource value: 0x7f060017
			public const int Donate = 2131099671;
			
			// aapt resource value: 0x7f060005
			public const int GetInTouch = 2131099653;
			
			// aapt resource value: 0x7f060015
			public const int HowToGetHelp = 2131099669;
			
			// aapt resource value: 0x7f060004
			public const int KidsZone = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int MakeAppointment = 2131099650;
			
			// aapt resource value: 0x7f06000d
			public const int MoreCarerInfo = 2131099661;
			
			// aapt resource value: 0x7f060006
			public const int MoreInfo = 2131099654;
			
			// aapt resource value: 0x7f060019
			public const int MyAppointments = 2131099673;
			
			// aapt resource value: 0x7f060018
			public const int MyNYAS = 2131099672;
			
			// aapt resource value: 0x7f06000a
			public const int NotFair = 2131099658;
			
			// aapt resource value: 0x7f06001b
			public const int Options = 2131099675;
			
			// aapt resource value: 0x7f060022
			public const int Pin = 2131099682;
			
			// aapt resource value: 0x7f060026
			public const int PinConfirmed = 2131099686;
			
			// aapt resource value: 0x7f06001d
			public const int PinInstructions = 2131099677;
			
			// aapt resource value: 0x7f060016
			public const int RateOurService = 2131099670;
			
			// aapt resource value: 0x7f060009
			public const int SchoolProblems = 2131099657;
			
			// aapt resource value: 0x7f060010
			public const int SpecialCharacter1 = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int SpecialCharacter2 = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int SpecialCharacter3 = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int SpecialCharacter4 = 2131099667;
			
			// aapt resource value: 0x7f060003
			public const int ViewAppointments = 2131099651;
			
			// aapt resource value: 0x7f060014
			public const int WhatsNYAS = 2131099668;
			
			// aapt resource value: 0x7f060024
			public const int WrongPin = 2131099684;
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int feelingBlue = 2131099656;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int calendarTextStyle = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
